name: onitama
description: "A new Flutter project."

publish_to: "none"

version: 1.3.0+4

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  http: ^1.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_mobile_ads: ^5.0.0
  cached_network_image: ^3.4.1
  firebase_crashlytics: ^5.0.3
  firebase_analytics: ^12.0.3
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  ios: true
  image_path: "assets/icons/icon.png"
